### PR TITLE
Fix Bug 1263445 - default ios version should be 3.0 instead of 2.0 in release notes

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by kyoshino** [comment]
```
src/_pylibmcmodule.h:42:36: fatal error: libmemcached/memcached.h: No such file or directory
```
:confused:

**Comment by jgmize** [comment]
The Circleci failure should be fixed by #4059

**Comment by jpetto** [comment]
Looks good to me! :lollipop: 

Waiting on current build to finish before merging...

**Comment by pollti** [comment]
Thank you very much!
